; Use with PSYQ under C:\Psyq (junction: mklink /J C:\Psyq <real-root>)
[ccpsx]
stdlib=libc.lib libapi.lib libsn.lib
compiler_path=C:\Psyq\bin
assembler_path=C:\Psyq\bin
linker_path=C:\Psyq\bin
library_path=C:\Psyq\psx\lib
c_include_path=C:\Psyq\psx\include
cplus_include_path=C:\Psyq\psx\include
